### ISSUE TITLE
Mono files play back an octave up

### ISSUE THREAD

**Issue by moshang** [Nidre/Unity-Audio-Sequencer#1]
Thanks for your work on the sequencer - it's proving super useful for a current project.

In my testing, mono .wav files are playing back an octave up (or twice as fast).

**Comment by Ludomancer** [comment]
Hmm, I've never tested this against mono audio to be honest. I will take to look into it, but unfortunately can't promise a date. Having a pretty busy schedule with my other projects currently.

**Comment by Ludomancer** [comment]
There is a chance that this might be caused by https://github.com/Nidre/Unity-Audio-Sequencer/issues/2 because if you have only changed the line 629, bpm and some other calculations are still based on signatureLo variable.

I will still make some tests with some mono files tho, I am just writing this so until I have time to take a look, it may help you to move forward. 

In short terms could you please try changing the line 629 back to its original state and let me know if that solves the problem.

Thank you for your time.

**Comment by moshang** [comment]
I've tried it with the original code, but the behavior is the same - mono files play an octave up. Hopefully I can fiddle around with the code myself for a solution, but in the meantime the workaround is to use stereo samples.

I'd ideally also like to change the behavior where samples get truncated to the length of the time signature - ie. with signatureLo set to 16, a sample will only sound for the duration of a sixteenth whether the step after it is active or not. I'd like the sample to ring out unless it gets cut off by a retrigger. 

But yeah, finding time... :^)

**Comment by Ludomancer** [comment]
@moshang I will be able to push a fix today. Stay tuned.

**Comment by Ludomancer** [comment]
@moshang 

Should be working properly on version 0.2. 

I have tested with the Sample scene by using Force Mono in Unity.

Let me know if that fixes your problem.

**Comment by moshang** [comment]
Great, that fixed it - thanks a lot!
