### ISSUE TITLE
Sequences of any length

### ISSUE THREAD

**Issue by moshang** [Nidre/Unity-Audio-Sequencer#2]
The playback length of the sequence is currently tied to the time signature, meaning it doesn't necessarily play all the steps in the sequence. More intuitive is to make the playback length the same as the length of the sequence.

I fixed this for myself by changing line 629 in Sequencer.cs from 
`if (++_currentStep > signatureLo)`
to
`if (++_currentStep > sequence.Length)`

**Comment by Ludomancer** [comment]
I will take a look into it. Thanks for letting me know.

**Comment by Ludomancer** [comment]
@moshang 

You seem to be right about that. but I haven't had the chance to fully inspect the reasons why I have used two separate variables for that. Array lenght and signatureLo. If there is no good reason, I will update as you have suggested.

However in the mean time, If you want to do this change in your repo, I would suggest you to replace all instances of signatureLo with sequence.Lenght since signatureLo is used in multiple places for important calculations. If you have only changed it in the line 629 it might and probably will cause problems.

**Comment by Ludomancer** [comment]
@moshang

The change you've suggested has been implemented in Version 0.3. Thanks for the suggestion!
